server:
  port: 8083
spring:
  profiles: dev
  application:
    name: blogservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.130.29.46:3306/dp_pojo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123321
  cloud:
    nacos:
      server-addr: 8.130.29.46:8848
      discovery:
        namespace: dev
  redis:
    host: 8.130.29.46
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 8.130.29.46
    port: 5672
    username: wei
    password: 123321
    virtual-host: /
mybatis-plus:
  type-aliases-package: com.example.blog.entity # 别名扫描包
logging:
  level:
    com.example.user: debug