server:
  port: 8081
spring:
  profiles: dev
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dp_pojo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ww20010208
  cloud:
    nacos:
      server-addr: 8.130.51.5:8848
  redis:
    host: 120.79.211.228
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 120.79.211.228
    port: 5672
    username: wei
    password: 123321
    virtual-host: /
  mail:
    host: smtp.qq.com
    username: haoxiang020@qq.com
    password: wjjdakiohhvlbcea
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
mybatis-plus:
  type-aliases-package: com.example.user.entity # 别名扫描包
logging:
  level:
    com.example.user: debug
email:
  subject: "登录验证码"
  context:
    prefix: "欢迎您访问好享，您的登录验证码为："
    suffix: "注意：有效时间2分钟"
upload:
  path: "C:\\Users\\wangwei\\Desktop\\nginx-1.18.0\\html\\haoxiang\\files\\"