server:
  port: 8081
spring:
  application:
    name: dppojo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dp_pojo?useSSL=false&serverTimezone=UTC
    username: root
    password: ww20010208
  redis:
    host: 192.168.10.100
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 192.168.10.100
    port: 5672
    username: itcast
    password: 123321
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true #true：调用returnCallback， false： 直接丢弃
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2 #下一次失败等待时长倍数
          max-attempts: 3 #最大重试3次
          stateless: false  #有状态， 包含事务
  mail:
    host: smtp.qq.com
    username: haoxiang020@qq.com
    password: wjjdakiohhvlbcea
mybatis-plus:
  type-aliases-package: com.dppojo.entity # 别名扫描包
logging:
  level:
    com.dppojo: debug
email:
  subject: "登录验证码"
  context:
    prefix: "欢迎您访问好享，您的登录验证码为："
    suffix: "注意：有效时间2分钟"
upload:
  path: "C:\\Users\\wangwei\\IdeaProjects\\nginx-1.18.0\\html\\haoxiang\\imgs\\"