server:
  port: 10010 # 网关端口
spring:
  profiles: dev
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: 120.79.211.228:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**, /upload/**, /chat/**
        - id: shop-service
          uri: lb://shopservice
          predicates:
            - Path=/shop/**, /shop-type/**, /voucher/**, /voucher-order/**
        - id: blog-service
          uri: lb://blogservice
          predicates:
            - Path=/follow/**, /blog/**, /blog-comments/**
  redis:
    host: 120.79.211.228
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
#      default-filters:
#        - AddRequestHeader=origin,gateway
#            - After=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
#     允许跨域请求
#      globalcors: # 全局的跨域处理
#        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: # 允许哪些网站的跨域请求
#              - "http://localhost:8090"
#            allowedMethods: # 允许的跨域ajax的请求方式
#              - "GET"
#              - "POST"
#              - "DELETE"
#              - "PUT"
#              - "OPTIONS"
#            allowedHeaders: "*" # 允许在请求中携带的头信息
#            allowCredentials: true # 是否允许携带cookie
#            maxAge: 360000 # 这次跨域检测的有效期

