server:
  port: 8082
spring:
  profiles: dev
  application:
    name: shopservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dp_pojo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ww20010208
  cloud:
    nacos:
      server-addr: 8.130.51.5:8848
  redis:
    host: 8.130.51.5
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 8.130.51.5
    port: 5672
    username: wei
    password: 123321
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true #true：调用returnCallback， false： 直接丢弃
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2 #下一次失败等待时长倍数
          max-attempts: 3 #最大重试3次
          stateless: false  #有状态， 包含事务
mybatis-plus:
  type-aliases-package: com.example.shop.entity # 别名扫描包
logging:
  level:
    com.example.shop: debug